# builds flux, runs the integration tests, signs the jars, and stages them in maven-central.
version: 0.2
env:
  secrets-manager:
    GPG_KEY_ID: "gpg-signing-key-id"
    GPG_PASSPHRASE: "gpg-signing-key-passphrase"
    GPG_PRIVATE_KEY: "gpg-signing-key-private-key"
    MAVEN_CENTRAL_USERNAME: "MavenCentral:username"
    MAVEN_CENTRAL_PASSWORD: "MavenCentral:password"
phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - mkdir -p ~/.m2/
      - echo "<settings><servers><server><id>central</id>" > ~/.m2/settings.xml
      - echo "<username>${MAVEN_CENTRAL_USERNAME}</username><password>${MAVEN_CENTRAL_PASSWORD}</password>" >> ~/.m2/settings.xml
      - echo "</server></servers></settings>" >> ~/.m2/settings.xml
  build:
    commands:
      - mvn deploy -P release